//! One-to-one encoding of legalized scalar machine operations.
use crate::ir::mir::value::Scalar;
use crate::wasmgen::wasm_builder::WasmBuilder;
pub(super) fn emit(w: &mut WasmBuilder, operation: Scalar) {
    match operation {
        Scalar::I32Add => w.add_i32(),
        Scalar::I32Sub => w.sub_i32(),
        Scalar::I32Mul => w.mul_i32(),
        Scalar::I32And => w.and_i32(),
        Scalar::I32Or => w.or_i32(),
        Scalar::I32Xor => w.xor_i32(),
        Scalar::I32Shl => w.shl_i32(),
        Scalar::I32Shr => w.shr_u_i32(),
        Scalar::I32Sar => w.shr_s_i32(),
        Scalar::I32Eq => w.eq_i32(),
        Scalar::I32Ult => w.ltu_i32(),
        Scalar::I32Slt => w.lt_i32(),
        Scalar::I32Clz => w.clz_i32(),
        Scalar::I32Ctz => w.ctz_i32(),
        Scalar::I32Popcnt => w.popcnt_i32(),
        Scalar::I64Add => w.add_i64(),
        Scalar::I64Sub => w.sub_i64(),
        Scalar::I64Mul => w.mul_i64(),
        Scalar::I64And => w.and_i64(),
        Scalar::I64Or => w.or_i64(),
        Scalar::I64Xor => w.xor_i64(),
        Scalar::I64Shl => w.shl_i64(),
        Scalar::I64Shr => w.shr_u_i64(),
        Scalar::I64Sar => w.shr_s_i64(),
        Scalar::I64Eq => w.eq_i64(),
        Scalar::I64Ult => w.ltu_i64(),
        Scalar::I64Slt => w.lt_i64(),
        Scalar::I64Clz => w.clz_i64(),
        Scalar::I64Ctz => w.ctz_i64(),
        Scalar::I64Popcnt => w.popcnt_i64(),
        Scalar::I32WrapI64 => w.wrap_i64_to_i32(),
        Scalar::I64ExtendSignedI32 => w.extend_signed_i32_to_i64(),
        Scalar::I64ExtendUnsignedI32 => w.extend_unsigned_i32_to_i64(),
        Scalar::Select => w.select(),
    }
}
