#!/usr/bin/env node
// Builds the CPU benchmark suite (tests/bench) into PE images linked at
// 0x400000 and the benchmark BIOS. Requires nasm and the MinGW-w64 i686
// toolchain (i686-w64-mingw32-gcc/ld). Output: build/bench/.
import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), "../..");
const src = path.join(root, "tests/bench");
const out = path.join(root, "build/bench");
const suite = JSON.parse(fs.readFileSync(path.join(src, "suite.json"), "utf8"));
const CC = process.env.BENCH_CC || "i686-w64-mingw32-gcc";
const LD = process.env.BENCH_LD || "i686-w64-mingw32-ld";
const COMMON = ["-ffreestanding", "-fno-asynchronous-unwind-tables", "-fno-stack-protector",
    "-fno-pic", "-fno-common", "-Wall", "-Wno-unused-function", "-I", path.join(src, "lib")];

fs.mkdirSync(out, { recursive: true });
const run = (tool, args) => execFileSync(tool, args, { stdio: ["ignore", "pipe", "inherit"] });
const stale = (target, sources) => !fs.existsSync(target) ||
    sources.some(s => fs.statSync(s).mtimeMs > fs.statSync(target).mtimeMs);

// gcc-like large code footprint: many distinct functions with branches, local
// arithmetic and a few direct calls, dispatched in a data-dependent order.
function codebloat() {
    let seed = 2024;
    const rand = n => { seed = (Math.imul(seed, 1103515245) + 12345) >>> 0; return (seed >>> 8) % n; };
    const ops = ["x += y * %d;", "x ^= x >> %d;", "y = y * 31 + x + %d;", "x = (x << %d) | (x >> 3);",
        "if(x & %d) y ^= x; else x += y;", "x -= y & %d;", "y += (x & 255) * %d;", "if((y ^ x) > %d) x = ~x;"];
    const n = 600;
    let s = "// Generated by tools/bench/build.mjs: 600 functions, large code footprint.\n#include \"bench.h\"\n";
    for (let i = 0; i < n; i++) s += `NOINLINE u32 f${i}(u32 x, u32 y, u32 depth);\n`;
    for (let i = 0; i < n; i++) {
        s += `NOINLINE u32 f${i}(u32 x, u32 y, u32 depth)\n{\n`;
        for (let k = 0, m = 4 + rand(10); k < m; k++) s += "    " + ops[rand(ops.length)].replace("%d", 1 + rand(29)) + "\n";
        s += `    if(depth && (x & 3) == ${rand(4)}) x += f${rand(n)}(y, x, depth - 1);\n`;
        s += `    for(u32 i = 0; i < (y & ${[1, 3, 7][rand(3)]}); i++) x = x * 3 + i;\n    return x ^ y;\n}\n`;
    }
    s += `static u32 (*const table[${n}])(u32, u32, u32) = {${Array.from({ length: n }, (_, i) => `f${i}`).join(",")}};\n`;
    s += "u32 bench_main(u32 iterations)\n{\n    u32 h = 0, seed = 1;\n";
    s += "    for(u32 i = 0; i < iterations * 2048; i++) h = mix(h, table[lcg(&seed) % 600](h, i, 2));\n    return h;\n}\n";
    return s;
}

function compile(file, profile, object) {
    if (file.endsWith(".asm")) run("nasm", ["-f", "win32", "-I", path.join(src, "src") + "/", file, "-o", object]);
    else run(CC, [...suite.profiles[profile].split(" "), ...COMMON, "-c", file, "-o", object]);
}

const libgcc = run(CC, ["-print-libgcc-file-name"]).toString().trim();
run("nasm", ["-f", "bin", path.join(src, "lib/boot.asm"), "-o", path.join(out, "boot.bin")]);
const crt0 = path.join(out, "crt0.o");
compile(path.join(src, "lib/crt0.asm"), null, crt0);
const runtime = {};
const only = process.argv[2] ? new RegExp(process.argv[2]) : null;
const manifest = [];
for (const bench of suite.benchmarks) {
    if (only && !only.test(bench.name)) continue;
    const profile = bench.profile || "int";
    let file = bench.source.startsWith("@") ? path.join(out, bench.source.slice(1) + ".c") : path.join(src, "src", bench.source);
    if (bench.source === "@codebloat") {
        const text = codebloat();
        if (!fs.existsSync(file) || fs.readFileSync(file, "utf8") !== text) fs.writeFileSync(file, text);
    }
    const objects = [crt0];
    if (!file.endsWith(".asm")) {
        runtime[profile] ??= path.join(out, `rt.${profile}.o`);
        compile(path.join(src, "lib/rt.c"), profile, runtime[profile]);
        objects.push(runtime[profile]);
    }
    const object = path.join(out, `${bench.name}.o`), image = path.join(out, `${bench.name}.exe`);
    const inputs = [file, path.join(src, "lib/bench.h"), path.join(src, "suite.json"), path.join(src, "src/micro.inc")];
    if (stale(object, inputs)) compile(file, profile, object);
    objects.push(object);
    run(LD, ["-m", "i386pe", "--image-base=0x400000", "-e", "_start", "-o", image, ...objects, libgcc]);
    manifest.push({ ...bench, image: path.relative(root, image) });
    process.stdout.write(`${bench.name} `);
}
fs.writeFileSync(path.join(out, "manifest.json"), JSON.stringify({ boot: "build/bench/boot.bin", benchmarks: manifest }, null, 1));
console.log(`\nbuilt ${manifest.length} benchmarks into ${path.relative(root, out)}`);
