#!/usr/bin/env node
// Regenerates src/browser/glbridge/gl-webgpu/COVERAGE.md from the code itself.
//
// The table exists to answer "what is actually implemented" without anyone
// having to trust a hand-maintained list, so it is derived: the opcode set
// comes from the guest, the handler set from the executor's real dispatch
// table, and the approximations from the list below -- which is the one thing
// that has to be edited by hand, and is deliberately small enough to audit.
//
// Usage: node tools/gen_gl_coverage.cjs

"use strict";

const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "../src/browser/glbridge");
const constants = require(path.join(root, "gl-webgpu", "gl_constants.js"));
const wire = require(path.join(root, "gl-webgpu", "gl_wire.js"));
const executorModule = require(path.join(root, "gl-webgpu", "gl_executor.js"));
const { createFakeHost } = require(path.join(__dirname, "../tests/glbridge/gl_fake_gpu.js"));

/*
 * Opcodes whose handler exists but deliberately does not do the GL thing.
 * A code names the deviation in gl-webgpu/README.md; "C" means the record is
 * accepted and has no effect, either because it is a hint or because the guest
 * already resolved it.
 */
const CLASSIFIED = {
    DRAW_PIXELS: "D-15", COPY_PIXELS: "D-15",
    LINE_STIPPLE: "D-16",
    LOGIC_OP: "D-01",
    PUSH_ATTRIB: "C", POP_ATTRIB: "C",
    PUSH_CLIENT_ATTRIB: "C", POP_CLIENT_ATTRIB: "C",
    HINT: "C",
};

const { host } = createFakeHost();
const executor = new executorModule.GLWebGPUExecutor(null, { host });

const names = Object.keys(constants.GLFN)
    .sort((a, b) => constants.GLFN[a] - constants.GLFN[b]);

const rows = [];
for (const name of names) {
    const opcode = constants.GLFN[name];
    const signature = wire.SIGNATURES[name];
    const glName = signature ? "gl" + signature[0] : name;
    let className;
    if (!executor.handlers[opcode]) className = "MISSING";
    else if (CLASSIFIED[name] === "C") className = "C";
    else if (CLASSIFIED[name]) className = "B";
    else className = "A";
    rows.push({ opcode, name, glName, className,
                note: CLASSIFIED[name] && CLASSIFIED[name] !== "C" ?
                    CLASSIFIED[name] : "" });
}

const counts = rows.reduce((acc, row) => {
    acc[row.className] = (acc[row.className] || 0) + 1;
    return acc;
}, {});

const lines = [];
lines.push("# OpenGL entry-point coverage");
lines.push("");
lines.push("Generated by `node tools/gen_gl_coverage.cjs`. Do not hand-edit:");
lines.push("the opcode set comes from the guest DLL, the handler set from the");
lines.push("executor's real dispatch table, and only the approximation list inside");
lines.push("the generator is maintained by hand.");
lines.push("");
lines.push("Classes follow section 2.3 of the implementation plan:");
lines.push("");
lines.push("- **A** -- really implemented.");
lines.push("- **B** -- approximated, because WebGPU cannot express it exactly. The");
lines.push("  code names the deviation in [README.md](README.md).");
lines.push("- **C** -- accepted with no effect: a hint, or something the guest DLL");
lines.push("  already resolved before it reached the wire (`glPushAttrib` keeps its");
lines.push("  own stack and sends only the differences).");
lines.push("- **MISSING** -- no handler at all. The plan's M7 exit condition is zero");
lines.push("  of these.");
lines.push("");
lines.push("Counts: " +
    ["A", "B", "C", "MISSING"].filter(k => counts[k])
        .map(k => k + " " + counts[k]).join(", ") +
    " of " + rows.length + " opcodes.");
lines.push("");
lines.push("| Op | Record | GL entry point | Class |");
lines.push("| ---: | --- | --- | --- |");
for (const row of rows)
    lines.push("| " + row.opcode + " | `" + row.name + "` | `" + row.glName +
        "` | " + row.className + (row.note ? " (" + row.note + ")" : "") + " |");
lines.push("");
lines.push("## What this table does not cover");
lines.push("");
lines.push("The guest DLL exports more entry points than there are opcodes, because");
lines.push("many resolve entirely inside `openglproxy/opengl32_proxy.c` and never reach");
lines.push("the host: display lists are recorded and replayed there,");
lines.push("`glPushAttrib`/`glPopAttrib` operate on its shadow state and emit only");
lines.push("the differences, `GL_SELECT` and `GL_FEEDBACK` are software transforms");
lines.push("that never touch the GPU, and pixel-buffer-object pack/unpack offsets are");
lines.push("resolved before the transfer. Those belong to the guest's own tests.");
lines.push("");

fs.writeFileSync(path.join(root, "gl-webgpu", "COVERAGE.md"),
    lines.join("\n"));
console.log("wrote gl-webgpu/COVERAGE.md: " +
    Object.entries(counts).map(([k, v]) => k + "=" + v).join(" ") +
    " (" + rows.length + " opcodes)");
